### ISSUE TITLE
cffi install error

### ISSUE THREAD

**Issue by xncbf** [python-cffi/cffi#10]
Hello, I started failing the CI of a project that includes cffi today and I discovered that the project was moved to github today.
Is there any connection?
I use cffi version 1.15.1.

```
Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
[pipenv.exceptions.InstallError]:           main()
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
[pipenv.exceptions.InstallError]:           json_out['return_val'] = hook(**hook_input['kwargs'])
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
[pipenv.exceptions.InstallError]:           return hook(metadata_directory, config_settings)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
[pipenv.exceptions.InstallError]:           self.run_setup()
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
[pipenv.exceptions.InstallError]:           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
[pipenv.exceptions.InstallError]:           exec(code, locals())
[pipenv.exceptions.InstallError]:         File "<string>", line 481, in <module>
[pipenv.exceptions.InstallError]:         File "<string>", line 348, in run_setup
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
[pipenv.exceptions.InstallError]:           return distutils.core.setup(**attrs)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
[pipenv.exceptions.InstallError]:           _setup_distribution = dist = klass(attrs)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 303, in __init__
[pipenv.exceptions.InstallError]:           _Distribution.__init__(self, dist_attrs)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
[pipenv.exceptions.InstallError]:           self.finalize_options()
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 680, in finalize_options
[pipenv.exceptions.InstallError]:           ep(self)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 700, in _finalize_setup_keywords
[pipenv.exceptions.InstallError]:           ep.load()(self, ep.name, value)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 216, in cffi_modules
[pipenv.exceptions.InstallError]:           add_cffi_module(dist, cffi_module)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 71, in add_cffi_module
[pipenv.exceptions.InstallError]:           _add_c_module(dist, ffi, module_name, source, source_extension, kwds)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-4jbdj9st/overlay/lib/python3.10/site-packages/cffi/setuptools_ext.py", line 109, in _add_c_module
[pipenv.exceptions.InstallError]:           from cffi._shimmed_dist_utils import Extension, log, mkpath
[pipenv.exceptions.InstallError]:       ModuleNotFoundError: No module named 'cffi._shimmed_dist_utils'
[pipenv.exceptions.InstallError]:       [end of output]
```

**Comment by nitzmahone** [comment]
Sounds like you're not using the CFFI version you think you're using :wink: - perhaps you've got a `--pre` or something turned on? In any case, I assume the problem went away when we released 1.16.0rc2 that fixed the underlying issue that popped up in 1.16.0rc1. Thanks for the report!

[image](https://github.com/python-cffi/cffi/assets/6775756/e470daec-6d72-4a34-a865-82c7c2ce91e8)
