### ISSUE TITLE
Fix wheel builds on musllinux_1_2 containers

### ISSUE THREAD

**Issue by nitzmahone** [python-cffi/cffi#114]
The static wheel extension build is broken again under musllinux_1_2 - need to find a more stable configuration to smuggle through the right config to setuptools to ignore the packaged libffi headers/libs and always favor the one we built. Alpine makes that a bit of an extra challenge, since we can't reliably just remove the packaged ones without breaking busybox (and other tools), and its script-based `ldconfig` isn't usually capable enough to do what we need.

**Comment by nitzmahone** [comment]
(we're currently forcing wheel builds to use `musllinux_1_1`)

**Comment by DreamingRaven** [comment]
Hey I am also seeing an issue with using musl 1.2.

pyproject dependencies:
```
[dependency-groups]
dev = [
  "cffi>=1.17.1",
  "pip>=25.2",
  "pre-commit>=4.2.0",
  "elyra[all]>=4.0.0",
  "ruff>=0.11.10",
  "ipykernel>=6.30.1",
  "jupyterlab>=4.4.5",
  "rpds-py>=0.27.0",
  "jupyterlab-git>=0.51.2",
  "jupyter-server-ydoc",
  "nbclassic>=1.3.1"
]
```
system musl version:
```
musl-1.2.5-r10 x86_64 {musl} (MIT) [installed]
musl-dev-1.2.5-r10 x86_64 {musl} (MIT) [installed]
musl-utils-1.2.5-r10 x86_64 {musl} (MIT AND BSD-2-Clause AND GPL-2.0-or-later) [installed]
```
attempting argon2 import:
```
import argon2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/jupyter/.venv/lib/python3.12/site-packages/argon2/__init__.py", line 7, in <module>
    from . import exceptions, low_level, profiles
  File "/opt/jupyter/.venv/lib/python3.12/site-packages/argon2/low_level.py", line 17, in <module>
    from _argon2_cffi_bindings import ffi, lib
  File "/opt/jupyter/.venv/lib/python3.12/site-packages/_argon2_cffi_bindings/__init__.py", line 3, in <module>
    from ._ffi import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by mattip** [comment]
Is this fixed?

**Comment by nitzmahone** [comment]
Yeah, somehow closing this issue fell through the cracks, because everything's been building fine against musl 1.2 for a long time now.

The unrelated issue comment is almost certainly a borked sys.path and/or inherited system packages thing unique to the reporter's config- `argon2-cffi` is working just fine on stock Alpine + MUSL 1.2.5/1.2.6.
