### ISSUE TITLE
cffi relies on deprecated (now removed) distutils.msvc9compiler module

### ISSUE THREAD

**Issue by alex** [python-cffi/cffi#117]
In https://github.com/pypa/distutils/pull/287 this module was removed and in https://github.com/pypa/setuptools/pull/4606 that was incorporated into setuptools 74.

As a result, building cffi now fails with:

```
    Traceback (most recent call last):
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-bywibcpm\overlay\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 33, in <module>
        from distutils.msvc9compiler import MSVCCompiler
    ModuleNotFoundError: No module named 'distutils.msvc9compiler'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "D:\a\cryptography\cryptography\src\_cffi_src\build_openssl.py", line 60, in <module>
        ffi.emit_c_code(c_file)
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-bywibcpm\overlay\Lib\site-packages\cffi\api.py", line 695, in emit_c_code
        recompile(self, module_name, source,
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-bywibcpm\overlay\Lib\site-packages\cffi\recompiler.py", line 1546, in recompile
        ext = ffiplatform.get_extension(ext_c_file, module_name, **kwds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-bywibcpm\overlay\Lib\site-packages\cffi\ffiplatform.py", line 9, in get_extension
        from cffi._shimmed_dist_utils import Extension
      File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-bywibcpm\overlay\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 36, in <module>
        raise Exception("This CFFI feature requires setuptools on Python >= 3.12. Please install the setuptools package.") from ex
    Exception: This CFFI feature requires setuptools on Python >= 3.12. Please install the setuptools package.
```

**Comment by MarkCallow** [comment]
Given this issue is breaking my CI builds and the delays getting one or other of the PRs to fix it landed and released, I am looking to workaround the issue temporarily for my project. I did not write our Python interface and I lack Python expertise so I am seeing help here to find a workaround.

My project's `requirements.txt` has
```
cffi==1.15.1
setuptools==70.0.0
```
I would have thought the latter line would get me an older version of setuptools that still has `distutils.mscv9compiler` but I am getting the `ModuleNotFound` error.

The `setup` function in my project's `setup.py` which does `from setuptools import setup` has
```
    cffi_modules=["buildscript.py:ffibuilder"],
    ...
    install_requires=["cffi>=1.15.1"],
    ...
    setup_requires=["cffi>=1.15.1"],
```
It seems that cffi is unaware of my project's `setuptools` choice and is using the latest one.

How can I make it use my project's selected `setuptools` or prevent it using the latest one?

To the maintainers of cffi, please release a fix a.s.ap.

**Comment by Flow86** [comment]
Hi, I temporarily fixed my issues by using an environmentvariable `PIP_CONSTRAINT=constraint.txt` and adding `setuptools<74` into the file `constraint.txt`. that way the constraints also apply to any install/setup requirements

**Comment by arigo** [comment]
@nitzmahone see comments above.

**Comment by BLACKNOTES** [comment]
Pyclarity package depends on cffi and 2024 challenges of clarity is ongoing right now.
Only solution I find was installing pyclarity on Linux and running codes there. As cffi has no problem on Linux but problem persists on windows.

**Comment by MarkCallow** [comment]
> Hi, I temporarily fixed my issues by using an environmentvariable PIP_CONSTRAINT=constraint.txt and adding setuptools<74 into the file constraint.txt. that way the constraints also apply to any install/setup requirements

Thank you @Flow86. This worked for me too. I recommend anyone who is running their build from 'CMake' in GitHub Actions to use a full path for `constraint.txt`. I used `$env:RUNNER_TEMP/constraint.txt`.

**Comment by LeftMonster** [comment]
> Hi, I temporarily fixed my issues by using an environmentvariable `PIP_CONSTRAINT=constraint.txt` and adding `setuptools<74` into the file `constraint.txt`. that way the constraints also apply to any install/setup requirements

Same worked for me, Thanks. I'm curious why?

**Comment by Flow86** [comment]
> > Hi, I temporarily fixed my issues by using an environmentvariable `PIP_CONSTRAINT=constraint.txt` and adding `setuptools<74` into the file `constraint.txt`. that way the constraints also apply to any install/setup requirements
> 
> Same worked for me, Thanks. I'm curious why?

you can specify constraint files for the "simple" install (with `--constraint file.txt`) on the `pip install` command, but: and thats a big but: its not applied by pip to any build requirements - e.g if the package needs to be build locally since no binary is available, a "venv" is created for the build, and there the constraints do not apply at the moment and would use the broken combination of setuptools and cffi. if you use the environment variable, the venv also picks up the constraints and therefor it works.

**Comment by martin-vi** [comment]
Other windows source builds also fails because `distutils.msvc9compiler` is imported in `cffi._shimmed_dist_utils` ([link](https://github.com/python-cffi/cffi/blob/main/src/cffi/_shimmed_dist_utils.py#L32C1-L33C57)).
<details>

<summary>Traceback:</summary>

```
     Traceback (most recent call last):
        File "C:\Users\someuser\AppData\Local\Temp\pip-build-env-bxmv74jo\overlay\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 33, in <module>
          from distutils.msvc9compiler import MSVCCompiler
      ModuleNotFoundError: No module named 'distutils.msvc9compiler'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "c:\users\someuser\desktop\venv39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\someuser\desktop\venv39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\someuser\desktop\venv39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 191, in <module>
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\_distutils\core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\dist.py", line 283, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\_distutils\dist.py", line 279, in __init__
          self.finalize_options()
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\dist.py", line 635, in finalize_options
          ep(self)
        File "C:\ScaleSDK\Python39\lib\site-packages\setuptools\dist.py", line 655, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "C:\Users\someuser\AppData\Local\Temp\pip-build-env-bxmv74jo\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 216, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "C:\Users\someuser\AppData\Local\Temp\pip-build-env-bxmv74jo\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 71, in add_cffi_module
          _add_c_module(dist, ffi, module_name, source, source_extension, kwds)
        File "C:\Users\someuser\AppData\Local\Temp\pip-build-env-bxmv74jo\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 109, in _add_c_module
          from cffi._shimmed_dist_utils import Extension, log, mkpath
        File "C:\Users\someuser\AppData\Local\Temp\pip-build-env-bxmv74jo\overlay\Lib\site-packages\cffi\_shimmed_dist_utils.py", line 39, in <module>
          raise Exception("This CFFI feature requires distutils. Please install the distutils or setuptools package.") from ex
      Exception: This CFFI feature requires distutils. Please install the distutils or setuptools package.
      [end of output]
```
</details>
