### ISSUE TITLE
CFFI does not recognize typedef for structs

### ISSUE THREAD

**Issue by u3Izx9ql7vW4** [python-cffi/cffi#146]
I'm using the example given in the documentation: https://cffi.readthedocs.io/en/latest/using.html. 

```C
typedef struct { int x, y; } foo_t;
```
```python
from cffi import FFI
ffi = FFI()
from mypckg import lib

v = ffi.new("foo_t *", [1, 2])
```

Which gives the following error:
```bash
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/api.py", line 183, in _typeof
    result = self._parsed_types[cdecl]
             ~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'foo_t *'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/cparser.py", line 336, in _parse
    ast = _get_parser().parse(fullcsource)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
        ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pycparser/c_parser.py", line 1931, in p_error
    self._parse_error(
  File "/opt/homebrew/lib/python3.11/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:2:7: before: *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dan/Production/symlink/ufn/cfn/api/replay.py", line 20, in <module>
    v = ffi.new("foo_t *", [1, 2])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/api.py", line 266, in new
    cdecl = self._typeof(cdecl)
            ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/api.py", line 186, in _typeof
    result = self._typeof_locked(cdecl)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/api.py", line 171, in _typeof_locked
    type = self._parser.parse_type(cdecl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/cparser.py", line 552, in parse_type
    return self.parse_type_and_quals(cdecl)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/cparser.py", line 555, in parse_type_and_quals
    ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/cparser.py", line 338, in _parse
    self.convert_pycparser_error(e, csource)
  File "/opt/homebrew/lib/python3.11/site-packages/cffi/cparser.py", line 367, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: cannot parse "foo_t *"
<cdef source string>:2:7: before: *
```

my compilation looks like this:
```C
def compile():
    ffibuilder = FFI()
    ffibuilder.cdef("""typedef struct { int x, y; } foo_t;""")
    ffibuilder.set_source("ufn",
    """
    typedef struct { int x, y; } foo_t;
    """)
   ffibuilder.compile(
        verbose=True,
        debug=not optimized
    )
```
This is the bottom of the generated `.c` file:
```C

/************************************************************/


    typedef struct { int x, y; } foo_t;
    

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // foo_t
/*  1 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_foo_t(foo_t *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->x) | 0);  /* check that 'foo_t.x' is an integer */
  (void)((p->y) | 0);  /* check that 'foo_t.y' is an integer */
}
struct _cffi_align_typedef_foo_t { char x; foo_t y; };

static const struct _cffi_field_s _cffi_fields[] = {
  { "x", offsetof(foo_t, x),
         sizeof(((foo_t *)0)->x),
         _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "y", offsetof(foo_t, y),
         sizeof(((foo_t *)0)->y),
         _CFFI_OP(_CFFI_OP_NOOP, 1) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$foo_t", 0, _CFFI_F_CHECK_FIELDS,
    sizeof(foo_t), offsetof(struct _cffi_align_typedef_foo_t, y), 0, 2 },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "foo_t", 0 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  NULL,  /* no globals */
  _cffi_fields,
  _cffi_struct_unions,
  NULL,  /* no enums */
  _cffi_typenames,
  0,  /* num_globals */
  1,  /* num_struct_unions */
  0,  /* num_enums */
  1,  /* num_typenames */
  NULL,  /* no includes */
  2,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_ufn(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_ufn(void) { return NULL; }
#  else
     initufn(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_ufn(void)
{
  return _cffi_init("ufn", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initufn(void)
{
  _cffi_init("ufn", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
```

No compilation errors. 
Does anyone know why the `foo_t` is not recognized?

**Comment by mattip** [comment]
```diff
- ffi = FFI()
- from mypckg import lib
+ from mypckg import ffi, lib
```
